language: python
sudo: true
python: 3.5
cache:
  pip: true
git:
  depth: false

branches:
  - master
before_install:
  - pip install --upgrade pip setuptools wheel
  - chmod +x ./ComplementaryScripts/*deploy.sh
install:
  - pip install --upgrade memote

script:
  # - memote run --skip-unchanged
  - git checkout "${TRAVIS_BRANCH}"
  - ./ComplementaryScripts/travis_deploy.sh
